<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-04T18:20:13 IST" name="Suite" finished-at="2024-05-04T18:20:54 IST" duration-ms="40803">
    <groups>
    </groups>
    <test started-at="2024-05-04T18:20:13 IST" name="Main Test" finished-at="2024-05-04T18:20:54 IST" duration-ms="40803">
      <class name="testCases.Tests.MainTest">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:testCases.Tests.MainTest@28cda624]" started-at="2024-05-04T18:20:13 IST" name="launchApp" finished-at="2024-05-04T18:20:28 IST" duration-ms="15425" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="SubmitOrder()[pri:0, instance:testCases.Tests.MainTest@28cda624]" started-at="2024-05-04T18:20:28 IST" name="SubmitOrder" finished-at="2024-05-04T18:20:38 IST" duration-ms="9330" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="CloseBroswer()[pri:0, instance:testCases.Tests.MainTest@28cda624]" started-at="2024-05-04T18:20:38 IST" name="CloseBroswer" finished-at="2024-05-04T18:20:38 IST" duration-ms="237" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBroswer -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:testCases.Tests.MainTest@28cda624]" started-at="2024-05-04T18:20:38 IST" name="launchApp" finished-at="2024-05-04T18:20:52 IST" duration-ms="14494" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="VerifyProductInOrderHistory()[pri:0, instance:testCases.Tests.MainTest@28cda624]" started-at="2024-05-04T18:20:52 IST" name="VerifyProductInOrderHistory" finished-at="2024-05-04T18:20:53 IST" depends-on-methods="testCases.Tests.MainTest.SubmitOrder" duration-ms="1073" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyProductInOrderHistory -->
        <test-method is-config="true" signature="CloseBroswer()[pri:0, instance:testCases.Tests.MainTest@28cda624]" started-at="2024-05-04T18:20:53 IST" name="CloseBroswer" finished-at="2024-05-04T18:20:54 IST" duration-ms="189" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBroswer -->
      </class> <!-- testCases.Tests.MainTest -->
    </test> <!-- Main Test -->
    <test started-at="2024-05-04T18:20:13 IST" name="Error Validation test" finished-at="2024-05-04T18:20:54 IST" duration-ms="40740">
      <class name="testCases.Tests.ErrorValidations">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:testCases.Tests.ErrorValidations@73eb439a]" started-at="2024-05-04T18:20:13 IST" name="launchApp" finished-at="2024-05-04T18:20:27 IST" duration-ms="14607" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="getErrorMessageOfBlankPassword()[pri:0, instance:testCases.Tests.ErrorValidations@73eb439a]" started-at="2024-05-04T18:20:27 IST" name="getErrorMessageOfBlankPassword" finished-at="2024-05-04T18:20:28 IST" duration-ms="460" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getErrorMessageOfBlankPassword -->
        <test-method is-config="true" signature="CloseBroswer()[pri:0, instance:testCases.Tests.ErrorValidations@73eb439a]" started-at="2024-05-04T18:20:28 IST" name="CloseBroswer" finished-at="2024-05-04T18:20:28 IST" duration-ms="145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBroswer -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:testCases.Tests.ErrorValidations@73eb439a]" started-at="2024-05-04T18:20:28 IST" name="launchApp" finished-at="2024-05-04T18:20:37 IST" duration-ms="8917" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method retried="true" signature="getErrorMessageOfLogin()[pri:0, instance:testCases.Tests.ErrorValidations@73eb439a]" started-at="2024-05-04T18:20:37 IST" name="getErrorMessageOfLogin" finished-at="2024-05-04T18:20:38 IST" duration-ms="894" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email  password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.Tests.ErrorValidations.getErrorMessageOfLogin(ErrorValidations.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getErrorMessageOfLogin -->
        <test-method is-config="true" signature="CloseBroswer()[pri:0, instance:testCases.Tests.ErrorValidations@73eb439a]" started-at="2024-05-04T18:20:38 IST" name="CloseBroswer" finished-at="2024-05-04T18:20:38 IST" duration-ms="240" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBroswer -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:testCases.Tests.ErrorValidations@73eb439a]" started-at="2024-05-04T18:20:38 IST" name="launchApp" finished-at="2024-05-04T18:20:52 IST" duration-ms="14106" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="getErrorMessageOfLogin()[pri:0, instance:testCases.Tests.ErrorValidations@73eb439a]" started-at="2024-05-04T18:20:52 IST" name="getErrorMessageOfLogin" finished-at="2024-05-04T18:20:53 IST" duration-ms="789" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email  password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.Tests.ErrorValidations.getErrorMessageOfLogin(ErrorValidations.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getErrorMessageOfLogin -->
        <test-method is-config="true" signature="CloseBroswer()[pri:0, instance:testCases.Tests.ErrorValidations@73eb439a]" started-at="2024-05-04T18:20:53 IST" name="CloseBroswer" finished-at="2024-05-04T18:20:54 IST" duration-ms="194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBroswer -->
      </class> <!-- testCases.Tests.ErrorValidations -->
    </test> <!-- Error Validation test -->
  </suite> <!-- Suite -->
</testng-results>
